# Generated by Django 6.0 on 2026-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
