# Generated by Django 6.0 on 2026-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scent_base',
            field=models.TextField(blank=True, default='', help_text='Base notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_mid',
            field=models.TextField(blank=True, default='', help_text='Mid/heart notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_top',
            field=models.TextField(blank=True, default='', help_text='Top notes (comma-separated or short paragraph)'),
        ),
    ]
