# Generated by Django 6.0 on 2026-01-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_easypost_tracker_id_order_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='easypost_tracker_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_tracking_event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_updated_at',
        ),
    ]
